import type { StageId } from './stages';

export interface Book {
  title: string;
  author: string;
  year?: string;
  url?: string;
  free?: boolean;
  why: string;
  modules?: string[];
  stage: StageId | 'meta';
}

export const LIBRARY: Book[] = [
  {
    stage: 'fundamentos',
    title: 'Computer Systems: A Programmer\'s Perspective',
    author: 'Bryant & O\'Hallaron',
    year: '2015 (3rd ed)',
    why: 'CS:APP. Bíblia de como o computador realmente funciona. Capítulos 1-9 essenciais.',
    modules: ['01-01', '01-02', '01-14'],
  },
  {
    stage: 'fundamentos',
    title: 'Operating Systems: Three Easy Pieces',
    author: 'Remzi & Andrea Arpaci-Dusseau',
    free: true,
    url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
    why: 'OS:TEP. Único livro de OS genuinamente legível. Virtualization, concurrency, persistence.',
    modules: ['01-02', '01-11'],
  },
  {
    stage: 'fundamentos',
    title: 'Structure and Interpretation of Computer Programs',
    author: 'Abelson & Sussman',
    free: true,
    url: 'https://web.mit.edu/6.001/6.037/sicp.pdf',
    why: 'SICP. Se você só ler 1 livro de CS na vida, leia este. Abstração, recursão, interpretadores.',
    modules: ['01-06', '01-13'],
  },
  {
    stage: 'fundamentos',
    title: 'Crafting Interpreters',
    author: 'Robert Nystrom',
    free: true,
    url: 'https://craftinginterpreters.com/',
    why: 'Você implementa 2 interpreters do zero. Parsing, runtime, paradigmas.',
    modules: ['01-13'],
  },
  {
    stage: 'fundamentos',
    title: 'You Don\'t Know JS Yet',
    author: 'Kyle Simpson',
    free: true,
    url: 'https://github.com/getify/You-Dont-Know-JS',
    year: '2nd ed',
    why: '6 volumes. Volumes 1, 2, 4 obrigatórios pra fundamentos JS.',
    modules: ['01-07'],
  },
  {
    stage: 'fundamentos',
    title: 'The Art of Multiprocessor Programming',
    author: 'Herlihy & Shavit',
    why: 'Bíblia de concorrência. Memory models, lock-free, transactional memory.',
    modules: ['01-11'],
  },
  {
    stage: 'fundamentos',
    title: 'Cryptography Engineering',
    author: 'Ferguson, Schneier, Kohno',
    why: 'Referência prática de cripto aplicada. Hash, MAC, AEAD, PKI, side-channels.',
    modules: ['01-12'],
  },
  {
    stage: 'fundamentos',
    title: 'Mathematics for Machine Learning',
    author: 'Deisenroth, Faisal, Ong',
    free: true,
    url: 'https://mml-book.com/',
    why: 'Linear algebra, calculus, probability, optimization no nível certo pra eng.',
    modules: ['01-15'],
  },

  {
    stage: 'plataforma',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    year: '2017 (1st ed)',
    why: 'DDIA. Replicação, consistency, batch/stream, evolution. Leitura cumulativa pelos estágios 2-4.',
    modules: ['02-09', '04-01', '04-02', '04-09', '04-13'],
  },
  {
    stage: 'plataforma',
    title: 'PostgreSQL Internals',
    author: 'Egor Rogov',
    free: true,
    url: 'https://postgrespro.com/community/books/internals',
    why: 'Como Postgres funciona por dentro: MVCC, vacuum, WAL, buffer manager.',
    modules: ['02-09'],
  },
  {
    stage: 'plataforma',
    title: 'Database Internals',
    author: 'Alex Petrov',
    year: '2019',
    why: 'B-Tree, LSM-Tree, distributed DBs em paralelo. Complementa DDIA com mais profundidade de storage.',
    modules: ['02-09', '02-12', '02-16'],
  },
  {
    stage: 'plataforma',
    title: 'Web Application Hacker\'s Handbook',
    author: 'Stuttard & Pinto',
    why: 'Atacar pra defender. Auth, session, injection, business logic flaws.',
    modules: ['02-13', '03-08'],
  },
  {
    stage: 'plataforma',
    title: 'Introduction to Information Retrieval',
    author: 'Manning, Raghavan, Schütze',
    free: true,
    url: 'https://nlp.stanford.edu/IR-book/',
    why: 'BM25, inverted index, scoring. Base de search engines.',
    modules: ['02-15'],
  },

  {
    stage: 'producao',
    title: 'Site Reliability Engineering',
    author: 'Google (Beyer et al)',
    free: true,
    url: 'https://sre.google/sre-book/table-of-contents/',
    why: 'SLI/SLO/SLA, error budgets, postmortems. Define vocabulário moderno de ops.',
    modules: ['03-07', '03-15'],
  },
  {
    stage: 'producao',
    title: 'Systems Performance',
    author: 'Brendan Gregg',
    year: '2020 (2nd ed)',
    why: 'Bíblia de performance. USE method, flamegraphs, eBPF.',
    modules: ['01-14', '03-10'],
  },
  {
    stage: 'producao',
    title: 'High Performance Browser Networking',
    author: 'Ilya Grigorik',
    free: true,
    url: 'https://hpbn.co/',
    why: 'TCP, TLS, HTTP/2/3, WebRTC. Leitura sequencial recomendada.',
    modules: ['01-03', '03-09'],
  },
  {
    stage: 'producao',
    title: 'Kubernetes Up & Running',
    author: 'Burns, Beda, Hightower',
    why: 'Pragmatic. Pods, services, deployments, operators.',
    modules: ['03-03'],
  },
  {
    stage: 'producao',
    title: 'Programming Rust',
    author: 'Blandy & Orendorff',
    year: '2021 (2nd ed)',
    why: 'Ownership, borrowing, traits. Foundation pra 05-07/05-08 também.',
    modules: ['03-11'],
  },

  {
    stage: 'sistemas',
    title: 'Designing Distributed Systems',
    author: 'Brendan Burns',
    free: true,
    url: 'https://azure.microsoft.com/en-us/resources/designing-distributed-systems/',
    why: 'Patterns canônicos: sidecar, ambassador, leader election, scatter/gather.',
    modules: ['04-01', '04-04'],
  },
  {
    stage: 'sistemas',
    title: 'Domain-Driven Design',
    author: 'Eric Evans',
    year: '2003',
    why: 'O livro azul. Bounded contexts, ubiquitous language, aggregates.',
    modules: ['04-06', '04-07'],
  },
  {
    stage: 'sistemas',
    title: 'Building Event-Driven Microservices',
    author: 'Adam Bellemare',
    why: 'Kafka centric. Schema registry, change data capture, event sourcing.',
    modules: ['04-02', '04-03', '04-13'],
  },
  {
    stage: 'sistemas',
    title: 'Specifying Systems',
    author: 'Leslie Lamport',
    free: true,
    url: 'https://lamport.azurewebsites.net/tla/book.html',
    why: 'TLA+ pelo autor. Spec formal de algoritmos concorrentes/distribuídos.',
    modules: ['04-14'],
  },
  {
    stage: 'sistemas',
    title: 'Release It!',
    author: 'Michael Nygard',
    year: '2018 (2nd ed)',
    why: 'Padrões de estabilidade: bulkhead, circuit breaker, timeout, steady state.',
    modules: ['04-04', '03-15'],
  },

  {
    stage: 'amplitude',
    title: 'The Staff Engineer\'s Path',
    author: 'Tanya Reilly',
    year: '2022',
    why: 'Definitivo. Big picture thinking, project execution, levelling up others.',
    modules: ['05-03', '05-06'],
  },
  {
    stage: 'amplitude',
    title: 'Staff Engineer',
    author: 'Will Larson',
    year: '2021',
    why: 'Archetypes (tech lead, architect, solver, right hand). Promo cases reais.',
    modules: ['05-03'],
  },
  {
    stage: 'amplitude',
    title: 'An Elegant Puzzle',
    author: 'Will Larson',
    year: '2019',
    why: 'Engineering management adjacente ao Staff IC. Org design, technical debt.',
    modules: ['05-03'],
  },
  {
    stage: 'amplitude',
    title: 'Resilient Management',
    author: 'Lara Hogan',
    year: '2019',
    why: 'Comunicação, feedback, mentoria. Mesmo em IC track.',
    modules: ['05-06'],
  },
  {
    stage: 'amplitude',
    title: 'The Pragmatic Engineer',
    author: 'Gergely Orosz',
    url: 'https://newsletter.pragmaticengineer.com/',
    why: 'Newsletter. Calibration de mercado, big tech vs scale-ups, comp data.',
    modules: ['05-05', 'CAPSTONE-amplitude'],
  },
];

export const STAGE_BOOK_COUNT: Record<StageId, number> = {
  fundamentos: LIBRARY.filter((b) => b.stage === 'fundamentos').length,
  plataforma: LIBRARY.filter((b) => b.stage === 'plataforma').length,
  producao: LIBRARY.filter((b) => b.stage === 'producao').length,
  sistemas: LIBRARY.filter((b) => b.stage === 'sistemas').length,
  amplitude: LIBRARY.filter((b) => b.stage === 'amplitude').length,
};
